"""created spaceship seedfile

Revision ID: 4c2b0a4e4518
Revises: ce9007a22d8f
Create Date: 2023-04-19 16:26:24.763368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c2b0a4e4518'
down_revision = 'ce9007a22d8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spaceships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spaceships', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
