"""add relationships

Revision ID: ce9007a22d8f
Revises: c93738dd7dca
Create Date: 2023-04-17 10:30:32.635177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce9007a22d8f'
down_revision = 'c93738dd7dca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('astronauts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.Integer(), nullable=True))

    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('astronaut_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('spaceship_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_missions_astronaut_id_astronauts'), 'astronauts', ['astronaut_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_missions_spaceship_id_spaceships'), 'spaceships', ['spaceship_id'], ['id'])

    with op.batch_alter_table('spaceships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spaceships', schema=None) as batch_op:
        batch_op.drop_column('name')

    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_missions_spaceship_id_spaceships'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_missions_astronaut_id_astronauts'), type_='foreignkey')
        batch_op.drop_column('spaceship_id')
        batch_op.drop_column('astronaut_id')

    with op.batch_alter_table('astronauts', schema=None) as batch_op:
        batch_op.drop_column('weight')
        batch_op.drop_column('age')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
